package com.canwar.base.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * Themes Material 3 Builder
 * https://m3.material.io/theme-builder#/custom
 * */

val md_theme_light_primary = Color(0xFFA900A8)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD7F5)
val md_theme_light_onPrimaryContainer = Color(0xFF380038)
val md_theme_light_secondary = Color(0xFF216C2E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFA7F5A7)
val md_theme_light_onSecondaryContainer = Color(0xFF002106)
val md_theme_light_tertiary = Color(0xFF426915)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC2F18E)
val md_theme_light_onTertiaryContainer = Color(0xFF0F2000)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF3FFFA)
val md_theme_light_onBackground = Color(0xFF00201A)
val md_theme_light_surface = Color(0xFFF3FFFA)
val md_theme_light_onSurface = Color(0xFF00201A)
val md_theme_light_surfaceVariant = Color(0xFFEEDEE7)
val md_theme_light_onSurfaceVariant = Color(0xFF4E444B)
val md_theme_light_outline = Color(0xFF80747B)
val md_theme_light_inverseOnSurface = Color(0xFFB7FFEC)
val md_theme_light_inverseSurface = Color(0xFF00382E)
val md_theme_light_inversePrimary = Color(0xFFFFABF3)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFA900A8)
val md_theme_light_outlineVariant = Color(0xFFD1C2CB)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFABF3)
val md_theme_dark_onPrimary = Color(0xFF5B005B)
val md_theme_dark_primaryContainer = Color(0xFF810080)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD7F5)
val md_theme_dark_secondary = Color(0xFF8CD88D)
val md_theme_dark_onSecondary = Color(0xFF00390F)
val md_theme_dark_secondaryContainer = Color(0xFF00531A)
val md_theme_dark_onSecondaryContainer = Color(0xFFA7F5A7)
val md_theme_dark_tertiary = Color(0xFFA7D475)
val md_theme_dark_onTertiary = Color(0xFF1D3700)
val md_theme_dark_tertiaryContainer = Color(0xFF2D5000)
val md_theme_dark_onTertiaryContainer = Color(0xFFC2F18E)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF00201A)
val md_theme_dark_onBackground = Color(0xFF79F8DC)
val md_theme_dark_surface = Color(0xFF00201A)
val md_theme_dark_onSurface = Color(0xFF79F8DC)
val md_theme_dark_surfaceVariant = Color(0xFF4E444B)
val md_theme_dark_onSurfaceVariant = Color(0xFFD1C2CB)
val md_theme_dark_outline = Color(0xFF9A8D95)
val md_theme_dark_inverseOnSurface = Color(0xFF00201A)
val md_theme_dark_inverseSurface = Color(0xFF79F8DC)
val md_theme_dark_inversePrimary = Color(0xFFA900A8)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFABF3)
val md_theme_dark_outlineVariant = Color(0xFF4E444B)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFC727C4)
